package com.example.mood

enum class Screen {
    ONBOARDING,
    LOGIN,
    REGISTER,
    PROFESSION_SELECTION,
    STUDENT_EXAM_PROMPT,
    STUDENT_EXAM_INPUT,
    PROFESSION_DETAIL_PROMPT,
    PROFESSION_DETAIL_INPUT,
    MAIN_ANALYSIS,
    MOOD_CONFIRMATION,
    PLAN_DISPLAY,
    SPOTIFY_PLAYLIST_DURATION_PROMPT,
    MOOD_ANALYTICS,
    NIGHT_REVIEW,
    PROFILE
}