package com.example.mood

enum class Screen {
    LOGIN,
    PROFESSION_SELECTION,
    STUDENT_EXAM_PROMPT,
    STUDENT_EXAM_INPUT,
    PROFESSION_DETAIL_PROMPT,
    PROFESSION_DETAIL_INPUT,
    MAIN_ANALYSIS,
    MOOD_CONFIRMATION,
    SPOTIFY_PLAYLIST_DURATION_PROMPT,
    PLAN_DISPLAY
}